# 应用服务 WEB 访问端口
server:
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://plotmax.opencs.site:3306/hrm_db?useSSL=false&serverTimezone=UTC&characterEncoding=utf8
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  jackson:
    serialization:
      write-dates-as-timestamps: false
    date-format: yyyy-MM-dd HH:mm:ss


logging:
  level:
    site.opencs.plotmax.hrm.controller: DEBUG  # 替换成你的包名


mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      logic-delete-field: deleted  # 全局逻辑删除字段
      logic-delete-value: 1        # 逻辑已删除值
      logic-not-delete-value: 0    # 逻辑未删除值
app:
  security:
    jwt:
      secret: ThisIsAReallyLongSecretKeyUsedForHS512AlgorithmThatShouldBeAtLeast64BytesLongReallyLongLoneAgoLongLong!!!
      token-validity-ms: 86400000
      refresh-token-validity-ms: 2592000000
      permit-all-endpoints:
        - "/api/auth/**"
        - "/api/public/**"
        - "/swagger-ui/**"
        - "/v3/api-docs/**"

